const languageOptions = [
  { key: "Select a language", value: "" },
  { key: "Mandarin Taiwan", value: "mandarin-taiwan" },
  { key: "Mandarin Beijing", value: "mandarin-mainland" },
  { key: "Squliq Atayal", value: "squliq-atayal" },
];

const typeOptions = [
  { key: "Consonant", value: "consonant" },
  { key: "Vowel (Monophthong)", value: "vowel" },
];

const vowelMandarinOptions = [
  { key: "Select a vowel", value: "" },
  { key: "a", value: "a" },
  { key: "i", value: "i" },
  { key: "u", value: "u" },
  { key: "e", value: "e" },
  // { key: "o", value: "o" },
  { key: "y", value: "y" },
];

const vowelSquliqOptions = [
  { key: "Select a symbol", value: "" },
  { key: "ə", value: "ə" },
  { key: "o", value: "o" },
  { key: "e", value: "e" },
  { key: "i", value: "i" },
  { key: "u", value: "u" },
  { key: "ɨ", value: "ɨ" },
  { key: "a", value: "a" },
];

const consonantSquliqOptions = [
  { key: "Select a symbol", value: "" },
  { key: "ɣ", value: "ɣ" },
  { key: "ʔ", value: "ʔ" },
  { key: "n", value: "n" },
  { key: "ʦ", value: "ʦ" },
  { key: "q", value: "q" },
  { key: "s", value: "s" },
  { key: "ŋ", value: "ŋ" },
  { key: "l", value: "l" },
  { key: "r", value: "r" },
  { key: "j", value: "j" },
  { key: "x", value: "x" },
  { key: "z", value: "z" },
  { key: "t", value: "t" },
  { key: "k", value: "k" },
  { key: "ħ", value: "ħ" },
];

const consonantMandarinOptions = [
  { key: "Select a symbol", value: "" },
  { key: "p", value: "b", disabled: true },
  { key: "pʰ", value: "p", disabled: true },
  { key: "m", value: "m", disabled: true },
  { key: "f", value: "f", disabled: true },
  { key: "t", value: "d" },
  { key: "tʰ", value: "t" },
  { key: "n", value: "n" },
  { key: "l", value: "l" },
  { key: "k", value: "g" },
  { key: "kʰ", value: "k" },
  { key: "h", value: "h", disabled: true },
  { key: "tɕ", value: "j" },
  { key: "tɕʰ", value: "q" },
  { key: "ɕ", value: "x" },
  { key: "tʂ", value: "zh" },
  { key: "tʂʰ", value: "ch" },
  { key: "ʂ", value: "sh" },
  { key: "ʐ", value: "r" },
  { key: "ts", value: "z" },
  { key: "tsʰ", value: "c" },
  { key: "s", value: "s" },
  { key: "ŋ", value: "ng" },
  { key: "ɚ", value: "er" },
];

const consonantOptions = [
  { key: "Select a symbol (Zhuyin/IPA/Pinyin)", value: "" },
  { key: "ㄅ/p/b", value: "b", disabled: true },
  { key: "ㄆ/pʰ/p", value: "p", disabled: true },
  { key: "ㄇ/m/m", value: "m", disabled: true },
  { key: "ㄈ/f/f", value: "f", disabled: true },
  { key: "ㄉ/t/d", value: "d" },
  { key: "ㄊ/tʰ/t", value: "t" },
  { key: "ㄋ/n/n", value: "n" },
  { key: "ㄌ/l/l", value: "l" },
  { key: "ㄍ", value: "g" },
  { key: "ㄎ", value: "k" },
  { key: "ㄏ", value: "h", disabled: true },
  { key: "ㄐ", value: "j" },
  { key: "ㄑ", value: "q" },
  { key: "ㄒ", value: "x" },
  { key: "ㄓ", value: "zh" },
  { key: "ㄔ", value: "ch" },
  { key: "ㄕ", value: "sh" },
  { key: "ㄖ", value: "r" },
  { key: "ㄗ", value: "z" },
  { key: "ㄘ", value: "c" },
  { key: "ㄙ", value: "s" },
  { key: "ㄧ", value: "yi" },
  { key: "ㄨ", value: "wu" },
  { key: "ㄩ", value: "yu" },
  { key: "ㄚ", value: "a" },
  { key: "ㄛ", value: "o" },
  { key: "ㄜ", value: "e" },
  { key: "ㄝ", value: "ê" },
  { key: "ㄞ", value: "ai" },
  { key: "ㄟ", value: "ei" },
  { key: "ㄠ", value: "ao" },
  { key: "ㄡ", value: "ou" },
  { key: "ㄢ", value: "an" },
  { key: "ㄣ", value: "en" },
  { key: "ㄤ", value: "ang" },
  { key: "ㄥ", value: "eng" },
  { key: "ㄦ", value: "er" },
];

export {
  languageOptions,
  typeOptions,
  vowelMandarinOptions,
  consonantSquliqOptions,
  vowelSquliqOptions,
  consonantOptions,
  consonantMandarinOptions,
};
